server:
  port: 8080
  servlet:
    context-path: /ShopBookPTD

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book_store_angular?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      format_sql: false
      dialect: org.hibernate.dialect.MySQL8Dialect



